source 'https://rubygems.org'

gem 'sinatra'
gem 'mongo'
gem 'mongoid'
gem 'bson_ext'
gem 'haml'
gem 'compass'
gem 'sass'
gem 'bootstrap-sass', '~> 2.0.4.0'
gem 'passenger'
gem 'bundler'
gem 'weibo2'
gem 'rvm'
gem 'moped', '1.1.5'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'omniauth-github'
gem 'gearman-ruby'
gem 'redis'
gem 'maruku'
